# Generated by Django 6.0.6 on 2026-06-19 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rm_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_method', models.CharField(choices=[('rule_based', 'Rule-Based'), ('heuristics', 'Heuristics'), ('ml', 'ML Model')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused — awaiting RM review'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('current_stage', models.CharField(choices=[('sql', 'SQL Agent'), ('decision', 'Decision Agent'), ('recommendation', 'Recommendation Agent'), ('message', 'Message Agent'), ('done', 'Done')], default='sql', max_length=20)),
                ('batch_offset', models.IntegerField(default=0)),
                ('total_users_processed', models.IntegerField(default=0)),
                ('raw_users', models.JSONField(default=list)),
                ('scored_users', models.JSONField(default=list)),
                ('recommended_users', models.JSONField(default=list)),
                ('generated_messages', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('sql_agent_log', models.TextField(blank=True)),
                ('decision_agent_log', models.TextField(blank=True)),
                ('recommendation_agent_log', models.TextField(blank=True)),
                ('message_agent_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='rm_auth.rmuser')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
