# Generated by Django 6.0.6 on 2026-06-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('rm_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('sql_agent', 'SQL Agent'), ('decision_agent', 'Decision Agent'), ('recommendation_agent', 'Recommendation Agent'), ('message_agent', 'Message Agent')], max_length=30)),
                ('batch_offset', models.IntegerField(default=0)),
                ('original_data', models.JSONField(default=list, help_text='Full agent output before RM review')),
                ('approved_data', models.JSONField(default=list, help_text='Entries approved (and optionally edited) by RM')),
                ('removed_ids', models.JSONField(default=list, help_text='customer_ids removed by RM')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='rm_auth.rmuser')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Human Review',
                'verbose_name_plural': 'Human Reviews',
                'ordering': ['reviewed_at'],
                'unique_together': {('run', 'stage', 'batch_offset')},
            },
        ),
    ]
