# Generated by Django 6.0.6 on 2026-06-19 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_humanreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_offset', models.IntegerField(default=0)),
                ('customer_id', models.CharField(max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('offer', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('publish_failed', 'Publish Failed'), ('consumed', 'Consumed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_messages', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Queued Message',
                'verbose_name_plural': 'Queued Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('publish_attempt', 'Publish Attempt'), ('published', 'Published'), ('publish_failed', 'Publish Failed'), ('consumed', 'Consumed'), ('consume_failed', 'Consume Failed')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='message_queue.queuedmessage')),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['status', 'created_at'], name='message_que_status_443648_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['run', 'batch_offset'], name='message_que_run_id_cce944_idx'),
        ),
    ]
