# Generated by Django 6.0.6 on 2026-06-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('premium', 'Premium'), ('salary', 'Salary')], default='savings', max_length=20)),
                ('relationship_tenure_months', models.PositiveIntegerField(help_text='Number of months the customer has been with the bank')),
                ('existing_products', models.JSONField(default=list, help_text="e.g. ['Savings Account', 'Credit Card']")),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_id', models.CharField(help_text='Credit card identifier', max_length=30, unique=True)),
                ('cd_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cd_usage_above_80pct', models.BooleanField(default=False, help_text='True when current utilisation exceeds 80% of the limit')),
                ('cd_score', models.PositiveIntegerField(help_text='Card-specific credit score')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='customers.customerprofile')),
            ],
            options={
                'verbose_name': 'Credit Card History',
                'verbose_name_plural': 'Credit Card Histories',
                'ordering': ['customer', 'cd_id'],
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_loans', models.JSONField(default=list, help_text='Active loans with type, principal, and EMI')),
                ('previous_applications', models.JSONField(default=list, help_text='Past loan applications with status')),
                ('repayment_behavior', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('poor', 'Poor'), ('no_history', 'No History')], default='no_history', max_length=20)),
                ('credit_score', models.PositiveIntegerField(blank=True, help_text='Credit score (300–900), null if unavailable', null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='customers.customerprofile')),
            ],
            options={
                'verbose_name': 'Loan History',
                'verbose_name_plural': 'Loan Histories',
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the reference month')),
                ('total_monthly_credit', models.DecimalField(decimal_places=2, help_text='Total spend on all credit cards this month', max_digits=14)),
                ('recent_large_transactions', models.JSONField(default=list, help_text='Large CC transactions this month')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_transactions', to='customers.customerprofile')),
            ],
            options={
                'verbose_name': 'Credit Card Transaction',
                'verbose_name_plural': 'Credit Card Transactions',
                'ordering': ['-month'],
                'unique_together': {('customer', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the reference month')),
                ('total_monthly_credits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_monthly_debits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salary_credits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('average_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recent_large_transactions', models.JSONField(default=list, help_text='List of transactions above ₹50,000')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customerprofile')),
            ],
            options={
                'verbose_name': 'Transaction Data',
                'verbose_name_plural': 'Transaction Data',
                'ordering': ['-month'],
                'unique_together': {('customer', 'month')},
            },
        ),
    ]
