# Generated by Django 6.0.6 on 2026-06-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_queue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(max_length=80, unique=True)),
                ('to_number', models.CharField(max_length=30)),
                ('from_number', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_delivery', to='message_queue.queuedmessage')),
            ],
            options={
                'verbose_name': 'WhatsApp Delivery',
                'verbose_name_plural': 'WhatsApp Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
